<?php

/**
 * @var \SimplifiedMagento\FirstModule\Block\Display $block
 */

// Store Id
echo "<h3>Store Id</h3>";
echo $block->getStoreId();

// Store Code
echo "<h3>Store Code</h3>";
echo $block->getStoreCode();

// Website Id
echo "<h3>Website Id</h3>";
echo $block->getWebsiteId();

// Store Name
echo "<h3>Store Name</h3>";
echo $block->getStoreName();


// Store Url
echo "<h3>Store Url</h3>";
echo $block->getStoreUrl();

// Store Active
echo "<h3>Store Active</h3>";
echo $block->isStoreActive();