<table>
     <tr><a class="action primary" href="<?php echo $block->getUrl('sample/index/insert'); ?>">Add Record</a></tr>
     <tr>
          <th>Id</th>
          <th>Name</th>
          <th>Created At</th>
          <th>Updated At</th>
          <th colspan="2">Action</th>
     </tr>
 
     <?php
          $collection = $block->getResult();
          foreach($collection as $item){
     ?>
     <tr>
          <td><?php echo $item->getData('data_id'); ?></td>
          <td><?php echo $item->getData('data_title'); ?></td>
          <td><?php echo $item->getData('created_at'); ?></td>
          <td><?php echo $item->getData('updated_at'); ?></td>
          <td><a href="<?php echo $block->getUrl('sample/index/edit').'?id='.$item->getData('data_id'); ?>" class="action primary">Edit</a></td>
          <td><a href="<?php echo $block->getUrl('sample/index/delete').'?id='.$item->getData('data_id'); ?>" class="action primary">Delete</a></td>
     </tr>
     <?php } ?>
</table>