<div class="simplifiedmagento-custom-section"data-bind="scope: 'section'">
    <p data-bind="text: customsection().customdata"></p>
</div>
<script type="text/x-magento-init">
    {
    	"*": {
        	"Magento_Ui/js/core/app": {
            	"components": {
                	"section": {
                    	"component": "SimplifiedMagento_CustomSection/js/section"
                	}
            	}
        	}
    	}
    }
</script>