<?php
$product = $block->getProduct();
if ($product->getData('deal_status')) {
	$end_datetime = $product->getData('deal_date');
	$date =  date( "Y/m/d",strtotime($end_datetime));  
	$endstr= date(strtotime($date));
	$now_date = new DateTime('now', new DateTimeZone('Asia/Kolkata'));
    $now = $now_date->format('Y/m/d H:i:s');

?>
<script>

 function showtiming(dt,no)
{

 	var end = new Date(dt);
 	var now_date= new Date(no);

    var _second = 1000;
    var _minute = _second * 60;
    var _hour = _minute * 60;
    var _day = _hour * 24;
      flag_time = true;
    timer = '';
    setInterval(function(){showRemaining();},1000);

    function showRemaining() 
    {
        var date = no;
        var now = new Date(date);
        var de= now.getTime();
        if ( flag_time ) {
       	 timer = de;
        }
        var d = new Date(timer);
        currentYear = d.getFullYear();
        month = d.getMonth()+1;

        var currentDate = d.getDate();
        currentDate = currentDate < 10 ? '0'+currentDate : currentDate;

        var hours = d.getHours();
        var minutes = d.getMinutes();
        var seconds = d.getSeconds();

        minutes = minutes < 10 ? '0'+minutes : minutes;
        seconds = seconds < 10 ? '0'+seconds : seconds;
        var strTime = hours + ':' + minutes+ ':' + seconds; 
        timer = timer + 1000;
        var now_time = currentYear+'/' + month+'/' + currentDate + ' ' + strTime ;


        var now = new Date(now_time);

        var distance = end - now;

        if (distance < 0) {
             if (distance>-3) 
                {
                    location.reload(true); 
                    return;
                };

            clearInterval(timer);
            // document.getElementById('countdown').innerHTML = 'Completed';
            document.getElementById('countdown').innerHTML = 'No deal available.';


            return;
        }
        var days = Math.floor(distance / _day);
        var hours = Math.floor((distance % _day) / _hour);
        var minutes = Math.floor((distance % _hour) / _minute);
        var seconds = Math.floor((distance % _minute) / _second);
        var moretext = 'This deal available for only ';
        if (days <10)
        	{days = '0' + days;}
	    if (hours <10)
	        {hours = '0' + hours;}
	    if (minutes < 10)
	       { minutes = '0' + minutes;}
	    if (seconds < 10)
	        {seconds = '0' + seconds; }
	    if(days==00)
	    {
	                    dytext = '';   

	    }
	    else if(days==1)
	    {
	        dytext = '<span class="countdown-text">'+ days +' Day  </span>';   
	    }
	    else
	    {
	         dytext = '<span class="countdown-text">'+ days +' Days  </span>';    
	    }
	    if(hours==00) {
	        hrtext='';
	    }
	    else {
	        hrtext = '<span class="countdown-text">'+ hours + '</span>'+ ":";
	    }
	    if(minutes==00)
	    {
	        mintext='';
	    }else {
	              mintext = '<span class="countdown-text">'+ minutes +'</span>'+ ":";

	    }
	        sectext = '<span class="countdown-text">'+ seconds +'</span>';
	        document.getElementById('countdown').innerHTML = moretext + dytext + hrtext +  mintext + sectext;
	       flag_time = false;
	    }


}

</script>
<h1 style="color: #1979c3">
	<span id="countdown" class="countdown">
		<script>showtiming('<?php echo $date?>','<?php echo $now ?>')</script>
	</span>
</h1>
<?php } else { ?>
	<h1 style="color: #1979c3">No deal available.</h1>
<?php } ?>